# Generated by Django 4.1 on 2023-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_likepost_alter_post_caption_alter_post_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
